language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
script:
  - git clone https://github.com/scala-exercises/site.git site
  - pushd site; sbt 'definitions/publishLocal' 'runtime/publishLocal' 'compiler/publishLocal' 'sbt-exercise/publishLocal' ; popd
  - sbt test
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master
